services:
  postgres:
    build:
      context: .
      dockerfile: dac-db.dockerfile
    image: "dac-db"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - ./dac_db:${PGDATA}
    ports:
      - "5432:5432"
    restart: unless-stopped
    network_mode: "host"
    # networks:
    #   - server_default

# volumes:
#     dac_db:
#       external: true

# networks:
#   server_default:
#     external: true